"""Kinematic set-point MPC for one four-bar leg."""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
from numpy.typing import NDArray
from scipy.optimize import minimize

from .geometry import DEFAULT_LEG_PARAMETERS, LegParameters, foot_position
from .safety import DEFAULT_SAFETY_PARAMETERS, SafetyParameters, safety_margins

FloatArray = NDArray[np.float64]


@dataclass(frozen=True)
class MPCParameters:
    """Numerical settings and cost weights for Cartesian foot set-point regulation."""

    dt: float = 0.08
    horizon: int = 8
    velocity_limit: FloatArray = field(
        default_factory=lambda: np.array([1.20, 1.20, 1.50], dtype=float)
    )
    foot_setpoint_weight: float = 800.0
    posture_weight: float = 0.40
    velocity_weight: float = 0.03
    velocity_change_weight: float = 0.20
    terminal_foot_setpoint_weight: float = 2000.0
    max_iterations: int = 60
    tolerance: float = 1e-5


DEFAULT_MPC_PARAMETERS = MPCParameters()


def rollout(
    q0: FloatArray,
    controls: FloatArray,
    mpc_parameters: MPCParameters = DEFAULT_MPC_PARAMETERS,
) -> FloatArray:
    """Roll out ``q[k+1] = q[k] + dt * u[k]`` over the prediction horizon."""
    q = np.asarray(q0, dtype=float).copy()
    if q.shape != (3,):
        raise ValueError(f"q0 must have shape (3,), received {q.shape}.")

    controls = np.asarray(controls, dtype=float).reshape(mpc_parameters.horizon, 3)
    state_prediction = [q.copy()]
    for velocity in controls:
        q = q + mpc_parameters.dt * velocity
        state_prediction.append(q.copy())
    return np.asarray(state_prediction, dtype=float)


def objective(
    control_flat: FloatArray,
    q0: FloatArray,
    foot_setpoint: FloatArray,
    q_nominal: FloatArray,
    previous_velocity: FloatArray,
    leg_parameters: LegParameters = DEFAULT_LEG_PARAMETERS,
    mpc_parameters: MPCParameters = DEFAULT_MPC_PARAMETERS,
) -> float:
    """Evaluate set-point error, posture, effort, and smoothness over the horizon.

    ``foot_setpoint`` is one constant Cartesian reference point for the complete
    optimization horizon. This demonstration does not accept a time-indexed
    reference trajectory and therefore is not a trajectory-tracking controller.
    """
    controls = np.asarray(control_flat, dtype=float).reshape(mpc_parameters.horizon, 3)
    q_prediction = rollout(q0, controls, mpc_parameters)

    cost = 0.0
    previous = np.asarray(previous_velocity, dtype=float)
    for index in range(mpc_parameters.horizon):
        q_next = q_prediction[index + 1]
        foot_setpoint_error = foot_position(q_next, leg_parameters) - foot_setpoint
        posture_error = q_next - q_nominal
        velocity = controls[index]
        velocity_change = velocity - previous

        cost += mpc_parameters.foot_setpoint_weight * float(
            foot_setpoint_error @ foot_setpoint_error
        )
        cost += mpc_parameters.posture_weight * float(posture_error @ posture_error)
        cost += mpc_parameters.velocity_weight * float(velocity @ velocity)
        cost += mpc_parameters.velocity_change_weight * float(
            velocity_change @ velocity_change
        )
        previous = velocity

    terminal_setpoint_error = foot_position(q_prediction[-1], leg_parameters) - foot_setpoint
    cost += mpc_parameters.terminal_foot_setpoint_weight * float(
        terminal_setpoint_error @ terminal_setpoint_error
    )
    return float(cost)


def constraint_residuals(
    control_flat: FloatArray,
    q0: FloatArray,
    leg_parameters: LegParameters = DEFAULT_LEG_PARAMETERS,
    safety_parameters: SafetyParameters = DEFAULT_SAFETY_PARAMETERS,
    mpc_parameters: MPCParameters = DEFAULT_MPC_PARAMETERS,
) -> FloatArray:
    """Return nonlinear inequality residuals; feasible values are nonnegative."""
    q_prediction = rollout(
        q0,
        np.asarray(control_flat, dtype=float).reshape(mpc_parameters.horizon, 3),
        mpc_parameters,
    )
    residuals: list[float] = []
    for q in q_prediction[1:]:
        residuals.extend((q - leg_parameters.q_min).tolist())
        residuals.extend((leg_parameters.q_max - q).tolist())
        margins = safety_margins(q, leg_parameters, safety_parameters)
        residuals.append(margins["lateral_spread"])
        residuals.append(margins["four_bar_toggle"])
    return np.asarray(residuals, dtype=float)


def solve_mpc(
    q: FloatArray,
    foot_setpoint: FloatArray,
    q_nominal: FloatArray,
    warm_start: FloatArray | None = None,
    previous_velocity: FloatArray | None = None,
    leg_parameters: LegParameters = DEFAULT_LEG_PARAMETERS,
    safety_parameters: SafetyParameters = DEFAULT_SAFETY_PARAMETERS,
    mpc_parameters: MPCParameters = DEFAULT_MPC_PARAMETERS,
) -> tuple[FloatArray, FloatArray]:
    """Solve one constrained Cartesian set-point regulation problem.

    The returned horizon is a predicted motion generated by the optimizer. It is
    not a desired path or a time-parameterized reference trajectory.
    """
    q = np.asarray(q, dtype=float)
    foot_setpoint = np.asarray(foot_setpoint, dtype=float)
    q_nominal = np.asarray(q_nominal, dtype=float)
    if warm_start is None:
        warm_start = np.zeros((mpc_parameters.horizon, 3), dtype=float)
    if previous_velocity is None:
        previous_velocity = np.zeros(3, dtype=float)

    bounds = [
        (-float(mpc_parameters.velocity_limit[j]), float(mpc_parameters.velocity_limit[j]))
        for _ in range(mpc_parameters.horizon)
        for j in range(3)
    ]

    result = minimize(
        objective,
        np.asarray(warm_start, dtype=float).reshape(-1),
        args=(
            q,
            foot_setpoint,
            q_nominal,
            np.asarray(previous_velocity, dtype=float),
            leg_parameters,
            mpc_parameters,
        ),
        method="SLSQP",
        bounds=bounds,
        constraints={
            "type": "ineq",
            "fun": lambda controls: constraint_residuals(
                controls,
                q,
                leg_parameters,
                safety_parameters,
                mpc_parameters,
            ),
        },
        options={
            "maxiter": mpc_parameters.max_iterations,
            "ftol": mpc_parameters.tolerance,
            "disp": False,
        },
    )

    minimum_constraint = float(
        np.min(
            constraint_residuals(
                result.x,
                q,
                leg_parameters,
                safety_parameters,
                mpc_parameters,
            )
        )
    )
    if not result.success or minimum_constraint < -1e-6:
        raise RuntimeError(
            "MPC solver failed: "
            f"{result.message}; minimum constraint residual={minimum_constraint:.3e}."
        )

    controls = np.asarray(result.x, dtype=float).reshape(mpc_parameters.horizon, 3)
    return controls[0].copy(), controls
